#!/usr/bin/env python3
"""Write `unicode.mbt`: the code point ranges of every Unicode General_Category,
as the character-class bodies a `\\p{...}` escape is rewritten into.

The data is Python's own Unicode database, so the version this was generated
from is recorded in the file and in the table below it. Run it again when the
toolchain's Unicode version moves and commit what changes.
"""
import io
import pathlib
import sys
import unicodedata
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent

# The long names ECMA-262 gives the General_Category values (Table 69), by the
# short name each one aliases.
LONG = {
    "C": ["Other"],
    "Cc": ["Control", "cntrl"],
    "Cf": ["Format"],
    "Cn": ["Unassigned"],
    "Co": ["Private_Use"],
    "L": ["Letter"],
    "LC": ["Cased_Letter"],
    "Ll": ["Lowercase_Letter"],
    "Lm": ["Modifier_Letter"],
    "Lo": ["Other_Letter"],
    "Lt": ["Titlecase_Letter"],
    "Lu": ["Uppercase_Letter"],
    "M": ["Mark", "Combining_Mark"],
    "Mc": ["Spacing_Mark"],
    "Me": ["Enclosing_Mark"],
    "Mn": ["Nonspacing_Mark"],
    "N": ["Number"],
    "Nd": ["Decimal_Number", "digit"],
    "Nl": ["Letter_Number"],
    "No": ["Other_Number"],
    "P": ["Punctuation", "punct"],
    "Pc": ["Connector_Punctuation"],
    "Pd": ["Dash_Punctuation"],
    "Pe": ["Close_Punctuation"],
    "Pf": ["Final_Punctuation"],
    "Pi": ["Initial_Punctuation"],
    "Po": ["Other_Punctuation"],
    "Ps": ["Open_Punctuation"],
    "S": ["Symbol"],
    "Sc": ["Currency_Symbol"],
    "Sk": ["Modifier_Symbol"],
    "Sm": ["Math_Symbol"],
    "So": ["Other_Symbol"],
    "Z": ["Separator"],
    "Zl": ["Line_Separator"],
    "Zp": ["Paragraph_Separator"],
    "Zs": ["Space_Separator"],
}

# What may not be written as itself inside a character class, plus everything a
# reader could not see: those go out as `\u{...}`.
UNSAFE = set("\\]^-[")


def ranges():
    """{category: [(first, last)]}, with the one-letter families included."""
    found = defaultdict(list)
    for code in range(0x110000):
        # A surrogate is half of a code point, not one: an engine that matches
        # code points can never see one, and a MoonBit string cannot hold one.
        if 0xD800 <= code <= 0xDFFF:
            continue
        category = unicodedata.category(chr(code))
        if category == "Cn":
            continue
        keys = [category, category[0]]
        if category in ("Lu", "Ll", "Lt"):
            keys.append("LC")
        for key in keys:
            runs = found[key]
            if runs and runs[-1][1] == code - 1:
                runs[-1][1] = code
            else:
                runs.append([code, code])
    return found


def point(code):
    """One code point as it goes into a class body."""
    char = chr(code)
    if char in UNSAFE or unicodedata.category(char) in ("Cc", "Cf", "Cs", "Zl", "Zp"):
        return "\\u{%04X}" % code
    if code < 0x20 or code == 0x7F:
        return "\\u{%04X}" % code
    return char


def body(runs):
    out = []
    for first, last in runs:
        if first == last:
            out.append(point(first))
        else:
            out.append(point(first) + "-" + point(last))
    return "".join(out)


def main():
    found = ranges()
    lines = [
        "// Copyright 2026 Leo Cheng",
        "// SPDX-License-Identifier: Apache-2.0",
        "",
        "// Generated by `scripts/gen_unicode.py` from Unicode %s. Do not edit: run"
        % unicodedata.unidata_version,
        "// the script again when the version moves, and commit what changes.",
        "",
        "///|",
        "/// The Unicode version these ranges are from.",
        'pub let unicode : String = "%s"' % unicodedata.unidata_version,
        "",
        "///|",
        "/// Every General_Category, as the body of the character class a",
        "/// `\\p{...}` escape is rewritten into. Both the short name and the long",
        "/// names ECMA-262 gives it (Table 69) are keys.",
        "let categories : Map[String, String] = {",
    ]
    for short in sorted(found):
        text = body(found[short]).replace('"', '\\"')
        names = [short] + LONG.get(short, [])
        for name in names:
            lines.append('  "%s": "%s",' % (name, text))
    lines.append("}")
    lines.append("")
    out = ROOT / "unicode.mbt"
    io.open(out, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    total = sum(len(v) for v in found.values())
    print("wrote %s (%d categories, %d ranges, %d bytes)"
          % (out, len(found), total, out.stat().st_size))


if __name__ == "__main__":
    sys.exit(main())
